# ---

# create app user

- name: Create django user
  sudo: yes
  user: name=django generate_ssh_key=yes ssh_key_bits=2048 password={{django_sudo_pass}}

- name: Copy .bashrc for django user
  sudo: yes
  copy: src=bashrc dest=/home/django/.bashrc owner=django group=users mode=0644

- name: Copy etc-bash.bashrc for django user
  sudo: yes
  copy: src=etc-bash.bashrc dest=/etc/bash.bashrc

- name: Set bash as default shell
  sudo: yes
  command: chsh -s /bin/bash django

# create app dir

- name: Creates app directory
  sudo: yes
  file: path=/srv/django state=directory owner=django group=users mode=0755

# git checkout

- name: Get git root dir
  local_action: command git rev-parse --show-toplevel
  register: git_root
  tags:
    - src

- name: Creating archive
  local_action: command chdir={{git_root['stdout']}} git archive --format zip --output /tmp/webdev-setup.zip HEAD
  tags:
    - src

- name: Creates tmp directory for unpack
  sudo: yes
  file: path=/tmp/webdev-setup state=directory
  tags:
    - src

- name: Unpack release
  sudo: yes
  unarchive: dest=/tmp/webdev-setup src=/tmp/webdev-setup.zip
  tags:
    - src

- name: Move release src to /srv/django/
  sudo: yes
  command: cp -rf /tmp/webdev-setup/src /srv/django/
  tags:
    - src

- name: Chown the app dir
  sudo: yes
  file: path=/srv/django owner=django group=users recurse=yes
  tags:
    - src

# install requirements

- name: Copy requirements.txt
  sudo: yes
  copy: src=requirements.txt dest=/srv/django/django_requirements.txt owner=django group=users mode=0644

- name: Pip install django_requirements.txt
  sudo: yes
  pip: requirements=/srv/django/django_requirements.txt virtualenv=/srv/django/venv

- name: Chown the venv
  sudo: yes
  file: path=/srv/django/venv owner=django group=users recurse=yes

# create app dirs

- name: Copy ckeditor test fileset
  sudo: yes
  copy: src=media dest=/srv/django/venv/local/lib/python2.7/site-packages/ckeditor owner=django group=users

- name: Create ckeditor upload directory
  sudo: yes
  file: path=/srv/django/src/django/app/media/ckeditor_uploads state=directory owner=django group=users mode=0777

- name: Create static dir
  sudo: yes
  file: path=/srv/django/src/django/app/static state=directory owner=django group=users mode=0755

# copy local settings

- name: Copy local django settings
  sudo: yes
  template: src=deploy_local_settings.py dest=/srv/django/src/django/app/local_settings.py owner=django group=users mode=0644

# syncdb & migrate

- name: Django syncdb
  sudo: yes
  django_manage: command=syncdb app_path=/srv/django/src/django/ virtualenv=/srv/django/venv/

- name: Django migrate
  sudo: yes
  django_manage: command=migrate app_path=/srv/django/src/django/ virtualenv=/srv/django/venv/

- name: Django collectstatic
  sudo: yes
  django_manage: command=collectstatic app_path=/srv/django/src/django/ virtualenv=/srv/django/venv/
